baseURL = "https://www.adrianmoreno.info"
languageCode = "en-us"
theme = "adritian-free-hugo-theme"

# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

[[menu.header]]
name = "Sobre mi"
URL = "#about"
weight = 2

[[menu.header]]
name = "Proyectos"
URL = "/proyectos"
weight = 3

[[menu.header]]
name = "Carrusel"
URL = "/carrusel"
weight = 4

[[menu.header]]
name = "Television"
URL = "/tv"
weight = 5

[[menu.header]]
name = "Contacto"
URL = "#contact"
weight = 6

[[menu.footer]]
name = "Sobre mi"
URL = "#about"
weight = 2

[[menu.footer]]
name = "Proyectos"
URL = "/proyectos"
weight = 3

[[menu.footer]]
name = "Television"
URL = "/tv"
weight = 5

[[menu.footer]]
name = "Contacto"
URL = "#contact"
weight = 6


[params]

sections = [
    "showcase",
    "about",
    "education",
    "experience",
    "client-and-work",
    "testimonial",
    "contact",
    "newsletter",
]

homepageExperienceCount = 6

# controls vercel page insights - disabled by default
vercelPageInsights = false
vercelAnalytics = false

[params.google_analytics]
code = "UA-XXXXX-Y"
enabled = false
[params.google_tag_manager]
code = "GTM-XXXXX"
enabled = false

[params.logo]
text1 = "Victor"
text2 = "Galan"

[params.footer]
copyright = "© Adritian. Free Hugo theme by Adrián Moreno Peña."
[params.footer.radity_logo]
x = "img/general/design-and-code-radity.png"
_2x = "img/general/design-and-code-radity@2x.png"
alt = "Design & Code - Radity"


[markup.goldmark.renderer]
unsafe = true
